// <auto-generated />
using AppAutohouse.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppAutohouse.DAL.Migrations
{
    [DbContext(typeof(AutohouseContext))]
    [Migration("20210807192650_M3")]
    partial class M3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCAppAutohouse.DAL.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Audi is the most prominent car brand for designing the best car interiors, with easy and accessible controls. Its MMI infotainment system is among the best available amongst the other brands. This car brand has the biggest vehicle line ups from being super-mini to being supra huge with the best available diesel and hybrid engines making it prominent for road racing.",
                            Logo = "https://pngimg.com/uploads/car_logo/car_logo_PNG1640.png",
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "With a wide range of innovative vehicle model, this car brand is known for its reliability and luxury status. This automobile company has serves its customers with luxurious piloting on the roads, while making sure that comfort has been served, from its passenger vehicles to its SUV, it will always be a great ride.",
                            Logo = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/BMW.svg/270px-BMW.svg.png",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This car brand is attentive enough with it comes to detailing of their model, each model is well detailed with the best technological features as well as well-equipped model design. This car brand is the most stylish and comfortable amongst the other car brands in terms of its design and affordability with a favourable service cost.",
                            Logo = "https://cdn.freelogovectors.net/wp-content/uploads/2018/04/volkswagen-logo.png",
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("MVCAppAutohouse.DAL.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<double>("EngineSize")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TypeEngine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            EngineSize = 2.2000000000000002,
                            Model = "A6",
                            Price = 8500,
                            TypeEngine = "Petrol",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            EngineSize = 2.5,
                            Model = "A8",
                            Price = 13500,
                            TypeEngine = "Diesel",
                            Year = 2010
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            EngineSize = 3.2000000000000002,
                            Model = "X6",
                            Price = 20500,
                            TypeEngine = "Diesel",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("MVCAppAutohouse.DAL.Entities.Car", b =>
                {
                    b.HasOne("MVCAppAutohouse.DAL.Entities.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("MVCAppAutohouse.DAL.Entities.Brand", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
